require('hyprlua')
require('keys')
require('monitors')
require('blue_light_filter')
require('screenshot')
require('cursor')
require('window')
require('apps')
require('audio')
require('clipboard')
require('picture_in_picture')
require('workspace')
require('config')
require('rules')

